name = "DiagonalIndexing"
uuid = "d2677e01-3654-4f8a-9d1f-7a356cb83656"
authors = ["Ryan Bennink <benninkrs@outlook.com>"]
version = "0.3.0"

[compat]
julia = "1.6"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
